#!/usr/bin/env python3
"""
Generate a static Unicode -> GB2312 lookup table for HZK16 font rendering.
Output: C header file with sorted array for binary search.
"""

import sys

def main():
    entries = []

    # GB2312 covers zones 01-94, positions 01-94
    # Zone 01-09: symbols/punctuation
    # Zone 16-55: Level 1 CJK (3755 chars, sorted by pinyin)
    # Zone 56-87: Level 2 CJK (3008 chars, sorted by radical)
    for qu in range(1, 95):
        for wei in range(1, 95):
            gb_high = qu + 0xA0
            gb_low = wei + 0xA0
            gb_bytes = bytes([gb_high, gb_low])
            try:
                ch = gb_bytes.decode('gb2312')
                cp = ord(ch)
                if cp > 0x7F:  # Skip ASCII (handled separately)
                    entries.append((cp, gb_high, gb_low))
            except (UnicodeDecodeError, ValueError):
                pass

    # Sort by Unicode codepoint for binary search
    entries.sort(key=lambda x: x[0])

    print("/* Auto-generated by tools/gen_utf8_gb2312.py */")
    print("/* Unicode -> GB2312 lookup table, sorted by codepoint for binary search */")
    print(f"/* Total entries: {len(entries)} */")
    print("")
    print("#ifndef UTF8_GB2312_TABLE_H")
    print("#define UTF8_GB2312_TABLE_H")
    print("")
    print("#include <stdint.h>")
    print("#include <stddef.h>")
    print("")
    print(f"#define UNICODE_GB2312_TABLE_SIZE {len(entries)}")
    print("")
    print("typedef struct {")
    print("    uint16_t unicode;   /* Unicode code point */")
    print("    uint8_t  gb_high;   /* GB2312 high byte (qu + 0xA0) */")
    print("    uint8_t  gb_low;    /* GB2312 low byte  (wei + 0xA0) */")
    print("} unicode_gb2312_entry_t;")
    print("")
    print("static const unicode_gb2312_entry_t unicode_gb2312_table[] = {")

    for i, (cp, hi, lo) in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ""
        # Add comment for first entry and every 100 entries
        comment = ""
        if i % 100 == 0:
            try:
                ch = bytes([hi, lo]).decode('gb2312')
                comment = f"  /* U+{cp:04X} {ch} */"
            except:
                comment = f"  /* U+{cp:04X} */"
        print(f"    {{0x{cp:04X}, 0x{hi:02X}, 0x{lo:02X}}}{comma}{comment}")

    print("};")
    print("")
    print("#endif /* UTF8_GB2312_TABLE_H */")

if __name__ == "__main__":
    main()
